packages:
  all:
    variants: +mpi
    compiler: [clang, gcc, intel, pgi, xl, nag]
    providers:
      awk: [gawk]
      blas: [openblas]
      daal: [intel-daal]
      elf: [elfutils]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [jdk]
      lapack: [openblas]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [openmpi]
      opencl: [pocl]
      openfoam: [openfoam-com, openfoam-org, foam-extend]
      pil: [py-pillow]
      scalapack: [netlib-scalapack]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      jpeg: [libjpeg-turbo, libjpeg]
# custom variants
  python:
    variants: +shared~dbm
  cmake:
    buildable: false
    externals:
    - prefix: /usr/
      spec: cmake@3.16.3
    - prefix: /home/mclarsen/software/cmake-3.14.7/
      spec: cmake@3.14.7
  perl:
    buildable: false
    externals:
    - prefix: /usr/
      spec: perl
  openblas:
    buildable: false
    externals:
    - prefix: /usr/
      spec: openblas
  cuda:
    buildable: false
    externals:
    - prefix: /usr/
      spec: cuda@10.1
  mpich:
    buildable: false

    externals:
    - prefix: /usr/
      spec: mpich@3.3.2%gcc
