compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-gnu
    - gcc/8.2.0
    operating_system: cnl7
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: gcc@8.2.0
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-intel
    - intel/19.0.3.199
    operating_system: cnl7
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: intel@19.0.3.199 
    target: any
