packages:
  all:
    compiler: [gcc@8.2.0, intel@19.0.3.199]
    providers:
      mpi: [mpich]
      blas: [openblas]
      lapack: [openblas]
  mpich:
    version: [7.7.6]
    buildable: false
    providers: {}
    compiler: []
    externals:
    - modules:
      - cray-mpich/7.7.6
      spec: mpich@7.7.6
  openssl:
    buildable: false
    externals:
    - prefix: /usr
      spec: openssl
  intel-mkl:
    buildable: false
    externals:
    - prefix: /opt/intel
      spec: intel-mkl%intel@19.0.3.199
  perl:
    buildable: false
    externals:
    - prefix: /usr
      spec: perl
  cmake:
    buildable: false
    externals:
    - prefix: /project/projectdirs/alpine/software/cmake/3.14.6/
      spec: cmake@3.14.6
  python:
    variants: ~dbm
  pkg-config:
    buildable: false
    externals:
    - prefix: /usr
      spec: pkg-config
