compilers:
- compiler:
    extra_rpaths: []
    flags: {}
    modules:
     - gcc/7.1.0
    operating_system: centos7
    paths:
      cc: /opt/apps/gcc/7.1.0/bin/gcc
      cxx: /opt/apps/gcc/7.1.0/bin/g++
      f77: /opt/apps/gcc/7.1.0/bin/gfortran
      fc: /opt/apps/gcc/7.1.0/bin/gfortran
    spec: gcc@7.1.0
    target: x86_64
- compiler:
    extra_rpaths:
     - /opt/intel/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64_lin
    flags: {}
    modules:
     - intel/18.0.2
    operating_system: centos7
    paths:
      cc:  /opt/intel/compilers_and_libraries_2018.2.199/linux/bin/intel64/icc
      cxx:  /opt/intel/compilers_and_libraries_2018.2.199/linux/bin/intel64/icpc
      f77:  /opt/intel/compilers_and_libraries_2018.2.199/linux/bin/intel64/ifort
      fc:   /opt/intel/compilers_and_libraries_2018.2.199/linux/bin/intel64/ifort
    spec: intel@18.0.2
    target: x86_64
