packages:
  all:
    compiler:
    - gcc
    providers:
      mpi:
      - mvapich2
      blas: [openblas]
      lapack: [openblas]
  mvapich2:
    buildable: false
    externals:
    - prefix: /opt/intel/compilers_and_libraries_2017.4.196/linux/mpi/intel64/
      spec: mvapich2
  perl:
    buildable: false
    externals:
    - prefix: /usr
      spec: perl
  python:
    variants: ~dbm
  cmake:
    version: [3.9.6]
    variants: ~ncurses~openssl
  pkg-config:
    buildable: false
    externals:
    - prefix: /usr
      spec: pkg-config
