packages:
  all:
    compiler: [gcc]
    providers:
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
  netlib-lapack:
    buildable: false
    externals:
    - prefix: /usr/
      spec: netlib-lapack
  openmpi:
    buildable: false
    externals:
    - prefix: /usr
      spec: openmpi
  pkg-config:
    buildable: false
    externals:
    - prefix: /usr
      spec: pkg-config
  openssl:
    buildable: false
    externals:
    - prefix: /usr
      spec: openssl
  perl:
    buildable: false
    externals:
    - prefix: /usr
      spec: perl
  tar:
    buildable: false
    externals:
    - prefix: /usr
      spec: tar
