packages:
  all:
    compiler: [gcc, intel, pgi, clang, xl, nag]
    providers:
      awk: [gawk]
      blas: [openblas]
      daal: [intel-daal]
      elf: [elfutils]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [jdk]
      lapack: [openblas]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [openmpi]
      opencl: [pocl]
      openfoam: [openfoam-com, openfoam-org, foam-extend]
      pil: [py-pillow]
      scalapack: [netlib-scalapack]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      jpeg: [libjpeg-turbo, libjpeg]
  python:
    variants: ~dbm
  cmake:
    version: [3.9.6]
    variants: ~openssl~ncurses
  perl:
    buildable: false
    externals:
    - prefix: /usr
      spec: perl
  pkg-config:
    buildable: false
    externals:
    - prefix: /usr
      spec: pkg-config
# SNL toss3 openmpi
  openmpi:
    buildable: false

    externals:
    - modules:
      - openmpi-gnu/2.0
      spec: openmpi
