name: ascent
repo_url:  https://github.com/Alpine-DAV/ascent.git
# to do mod azemu to find current branch via git cmds
repo_branch: task/2022_06_amalgamate_vtk-h
default_container:  alpinedav/ascent-ci:ubuntu-18-devel