name: build_ascent_gcc

on:
  pull_request:
    branches: [ develop ]

jobs:
  build_basic:
    name: Ubuntu Build Ascent GCC
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++
      FC: gfortran
    steps:
    - name: Install System Deps
      run: |
           sudo apt-get update
           sudo apt-get install binutils \
                                gcc \
                                g++ \
                                gfortran \
                                python3 \
                                perl \
                                git \
                                git-lfs \
                                curl \
                                wget \
                                tar \
                                unzip \
                                build-essential \
                                libncurses-dev \
                                libssl-dev \
                                libblas-dev \
                                liblapack-dev \
                                zlib1g-dev \
                                libgdbm-dev \
                                libreadline-dev \
                                libsqlite3-dev \
                                libbz2-dev \
                                mpich \
                                libmpich-dev
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup CMake
      run: |
        curl -L https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-x86_64.tar.gz -o cmake-3.23.2-linux-x86_64.tar.gz
        tar -xzf cmake-3.23.2-linux-x86_64.tar.gz
        export PATH=`pwd`/cmake-3.23.2-linux-x86_64/bin/:$PATH
        cmake --version
    - name: Build TPLs
      run: |
        export PATH=`pwd`/cmake-3.23.2-linux-x86_64/bin/:$PATH
        env enable_mpi=ON \
            enable_fortran=ON \
            enable_tests=OFF \
            enable_verbose=OFF \
            build_ascent=false \
            build_jobs=2 \
            ./scripts/build_ascent/build_ascent.sh
    - name: Configure Ascent
      run: |
        export PATH=`pwd`/cmake-3.23.2-linux-x86_64/bin/:$PATH
        cmake --version
        echo "**** Configuring Ascent"
        cmake -S src -B build -C ascent-config.cmake -DCMAKE_INSTALL_PREFIX=install
    - name: Build Ascent
      run: |
        export PATH=`pwd`/cmake-3.23.2-linux-x86_64/bin/:$PATH
        echo "**** Building Ascent"
        cmake --build  build -j2
    - name: Install Ascent
      run: |
        export PATH=`pwd`/cmake-3.23.2-linux-x86_64/bin/:$PATH
        echo "**** Installing Ascent"
        cmake --install  build
    - name: Check Install
      run: |
        export PATH=`pwd`/cmake-3.23.2-linux-x86_64/bin/:$PATH
        echo "**** Checking Ascent using-with-cmake-mpi example"
        export CC=/usr/bin/mpicc
        export CXX=/usr/bin/mpicxx
        cd install/examples/ascent/using-with-cmake-mpi
        cmake -S . -B build
        cmake --build  --verbose build -j2
        mpiexec -n 2 ./build/ascent_mpi_render_example
