name: build_ascent

on:
  pull_request:
    branches: [ develop ]

jobs:
  build_basic:
    strategy:
      matrix:
        include:
        - cc: gcc
          cxx: g++
          fc: gfortran
    name: Ubuntu Build Ascent (${{ matrix.cc }})
    runs-on: ubuntu-latest
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
      FC: ${{ matrix.fc }}
    steps:
    - name: Install System Deps
      run: |
           sudo apt-get update
           sudo apt-get install binutils \
                                gcc \
                                g++ \
                                gfortran \
                                python3 \
                                perl \
                                git \
                                git-lfs \
                                curl \
                                wget \
                                tar \
                                unzip \
                                build-essential \
                                libncurses-dev \
                                libssl-dev \
                                libblas-dev \
                                liblapack-dev \
                                zlib1g-dev \
                                libgdbm-dev \
                                libreadline-dev \
                                libsqlite3-dev \
                                libbz2-dev \
                                mpich \
                                libmpich-dev \
                                cmake
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build TPLs
      run: |
        env enable_mpi=ON \
            enable_fortran=ON \
            enable_tests=OFF \
            build_ascent=OFF \
            enable_verbose=OFF \
            build_jobs=2 \
            ./scripts/build_ascent/build_ascent.sh
    - name: Configure Ascent
      run: |
        echo "**** Configuring Ascent"
        cmake -S src -B build -C ascent-config.cmake -DCMAKE_INSTALL_PREFIX=install
    - name: Build Ascent
      run: |
        echo "**** Building Ascent"
        cmake --build  build -j2
    - name: Install Ascent
      run: |
        echo "**** Installing Ascent"
        cmake --install  build
    - name: Check Install
      run: |
        echo "**** Checking Ascent using-with-cmake-mpi example"
        export CC=/usr/bin/mpicc
        export CXX=/usr/bin/mpicxx
        cd install/examples/ascent/using-with-cmake-mpi
        cmake -S . -B build
        cmake --build  build -j2
        mpiexec -n 2 ./build/ascent_mpi_render_example
